spring:
    application:
      name: edu
    profiles:
      active: dev
    http:
        encoding:
            charset: utf-8
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
mybatis:
    type-aliases-package: com.code.edu.model
    mapper-locations: classpath:mappers/*.xml
    config-location:  classpath:mybatis/mybatis-config.xml
mapper:
    mappers: com.code.edu.tkmapper.BaseMapper
    not-empty: false
    identity: MYSQL