server:
    port: 8080
eureka:
    port: 8888
    host: 220.190.179.149
    client:
        serviceUrl:
            defaultZone: http://${eureka.host}:${eureka.port}/eureka/
spring:
    datasource:
        url: jdbc:mysql://220.190.179.149:3306/edu?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: czd102930
        driver-class-name: com.mysql.jdbc.Driver
debug: true

#logging.level.root: warn
#logging.level.root=INFO
#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate=ERROR
#logging.path=/home/_xyy_/output/SpringBootDemo/logs
#logging.level.org.springboot.sample=TRACE
logging:
    level:
        root: WARN
        org:
            springframework:
                web: DEBUG
            hibernate: ERROR
            springboot:
                sample: TRACE
        com:
            code:
                edu: INFO
    path: /usr/java/logs
#    config: classpath:logger/logback-spring.xml
#logging.file=demo.log
